In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('data2019.csv')
data.head()

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,OPTS
0,1.0,Atlanta Hawks,67,16280,2723,6067,0.449,805,2416,0.333,...,661,2237,2898,1605,523,341,1086,1548,7488,6736
1,2.0,Boston Celtics,64,15485,2634,5735,0.459,794,2190,0.363,...,683,2259,2942,1459,529,358,873,1367,7232,6818
2,3.0,Brooklyn Nets,64,15560,2558,5763,0.444,824,2423,0.340,...,694,2409,3103,1539,413,292,993,1322,7089,6837
3,4.0,Charlotte Hornets,65,15750,2425,5586,0.434,785,2231,0.352,...,715,2066,2781,1549,428,268,949,1223,6687,6903
4,5.0,Chicago Bulls,65,15675,2573,5762,0.447,793,2282,0.348,...,680,2041,2721,1510,652,265,1005,1417,6945,6932

In [3]:
#Taking the essential features
data = data.iloc[:,[1,2,5,14,16,22,24,25]]
data.head()

                Team   G   FGA   FTA  ORB   TOV   PTS  OPTS
0      Atlanta Hawks  67  6067  1566  661  1086  7488  6736
1     Boston Celtics  64  5735  1461  683   873  7232  6818
2      Brooklyn Nets  64  5763  1545  694   993  7089  6837
3  Charlotte Hornets  65  5586  1406  715   949  6687  6903
4      Chicago Bulls  65  5762  1332  680  1005  6945  6932

In [4]:
#Calculating Possessions of aevery team for the whole season
[row, col] = data.shape
for i in range(row):
    data.loc[i,'POS'] = ((data.loc[i,'FGA']+data.loc[i,'TOV'])-(data.loc[i,'ORB']+(0.4*data.loc[i,'FTA'])))
data.head()

                Team   G   FGA   FTA  ORB   TOV   PTS  OPTS     POS
0      Atlanta Hawks  67  6067  1566  661  1086  7488  6736  5865.6
1     Boston Celtics  64  5735  1461  683   873  7232  6818  5340.6
2      Brooklyn Nets  64  5763  1545  694   993  7089  6837  5444.0
3  Charlotte Hornets  65  5586  1406  715   949  6687  6903  5257.6
4      Chicago Bulls  65  5762  1332  680  1005  6945  6932  5554.2

In [5]:
data = data.iloc[:-1,:]

In [6]:
#Finding Offensive and Defensive Efficiency
[row, col] = data.shape
for i in range(row):
    data.loc[i,'OER'] = (data.loc[i,'PTS']/data.loc[i,'POS'])*100
    data.loc[i,'DER'] = (data.loc[i,'OPTS']/data.loc[i,'POS'])*100

In [7]:
#Finding League Average
oeravg = data.loc[:,'OER'].mean(axis=0)
deravg = data.loc[:,'DER'].mean(axis=0)
print(oeravg)
print(deravg)

132.64101854679228
132.734691294822

In [8]:
#Subtracting efficiency with league average and finding possesions per game
for i in range(row):
    data.loc[i,'Odiff'] = data.loc[i,'OER']-oeravg
    data.loc[i,'Ddiff'] = data.loc[i,'DER']-deravg
    data.loc[i,'Tempo'] = data.loc[i,'POS']/data.loc[i,'G']

In [9]:
#Finding league average possessions per game
tempoavg = data.loc[:,'Tempo'].mean(axis=0)
print(tempoavg)

84.05122739870687

In [10]:
#Subtracting possessions per game to league average
for i in range(row):
    data.loc[i,'Tdiff'] = data.loc[i,'Tempo']-tempoavg
data

,Team,G,FGA,FTA,ORB,TOV,PTS,OPTS,POS,OER,DER,Odiff,Ddiff,Tempo,Tdiff
0,Atlanta Hawks,67,6067,1566,661,1086,7488,6736,5865.6,127.659574,114.839062,-4.981444,-17.895630,87.546269,3.495041
1,Boston Celtics,64,5735,1461,683,873,7232,6818,5340.6,135.415496,127.663558,2.774478,-5.071133,83.446875,-0.604352
2,Brooklyn Nets,64,5763,1545,694,993,7089,6837,5444.0,130.216752,125.587803,-2.424266,-7.146888,85.062500,1.011273
3,Charlotte Hornets,65,5586,1406,715,949,6687,6903,5257.6,127.187310,131.295648,-5.453709,-1.439043,80.886154,-3.165074
4,Chicago Bulls,65,5762,1332,680,1005,6945,6932,5554.2,125.040510,124.806453,-7.600509,-7.928239,85.449231,1.398003
5,Cleveland Cavaliers,65,5715,1296,704,1073,6948,6977,5565.6,124.838292,125.359350,-7.802726,-7.375341,85.624615,1.573388
6,Dallas Mavericks,67,6027,1548,712,857,7796,6978,5552.8,140.397637,125.666330,7.756619,-7.068361,82.877612,-1.173615
7,Denver Nuggets,65,5778,1330,699,890,7176,6979,5437.0,131.984550,128.361229,-0.656468,-4.373463,83.646154,-0.405074
8,Detroit Pistons,66,5658,1476,644,1008,7078,6981,5431.6,130.311510,128.525665,-2.329508,-4.209027,82.296970,-1.754258
9,Golden State Warriors,65,5730,1511,647,969,6912,6984,5447.6,126.881563,128.203245,-5.759456,-4.531446,83.809231,-0.241997
10,Houston Rockets,64,5803,1664,663,939,7560,7019,5413.4,139.653453,129.659733,7.012434,-3.074958,84.584375,0.533148
11,Indiana Pacers,65,5744,1244,573,853,7107,7080,5526.4,128.600898,128.112334,-4.040121,-4.622358,85.021538,0.970311
12,Los Angeles Clippers,64,5739,1679,701,946,7436,7098,5312.4,139.974400,133.611927,7.333381,0.877236,83.006250,-1.044977
13,Los Angeles Lakers,63,5579,1496,668,951,7203,7126,5263.6,136.845505,135.382628,4.204486,2.647937,83.549206,-0.502021
14,Memphis Grizzlies,65,5913,1384,679,992,7321,7130,5672.4,129.063536,125.696354,-3.577483,-7.038337,87.267692,3.216465
15,Miami Heat,65,5486,1633,552,968,7290,7145,5248.8,138.888889,136.126353,6.247870,3.391661,80.750769,-3.300458
16,Milwaukee Bucks,65,5928,1562,617,969,7712,7240,5655.2,136.370066,128.023766,3.729048,-4.710926,87.003077,2.951850
17,Minnesota Timberwolves,64,5865,1624,675,981,7248,7313,5521.4,131.271054,132.448292,-1.369964,-0.286399,86.271875,2.220648
18,New Orleans Pelicans,64,5902,1485,719,1038,7436,7320,5627.0,132.148569,130.087080,-0.492449,-2.647611,87.921875,3.870648
19,New York Knicks,66,5896,1550,795,946,6983,7391,5427.0,128.671458,136.189423,-3.969561,3.454732,82.227273,-1.823955
20,Oklahoma City Thunder,64,5447,1589,517,861,7089,7391,5155.4,137.506304,143.364239,4.865286,10.629548,80.553125,-3.498102
21,Orlando Magic,65,5773,1434,674,820,6914,7405,5345.4,129.344857,138.530325,-3.296161,5.795634,82.236923,-1.814304
22,Philadelphia 76ers,65,5701,1435,673,923,7123,7409,5377.0,132.471638,137.790590,-0.169380,5.055898,82.723077,-1.328150
23,Phoenix Suns,65,5709,1560,637,980,7316,7461,5428.0,134.782609,137.453943,2.141590,4.719251,83.507692,-0.543535
24,Portland Trail Blazers,66,5998,1434,666,858,7500,7478,5616.4,133.537497,133.145787,0.896479,0.411096,85.096970,1.045742
25,Sacramento Kings,64,5622,1302,616,922,6975,7489,5407.2,128.994674,138.500518,-3.646345,5.765827,84.487500,0.436273
26,San Antonio Spurs,63,5638,1434,555,773,7129,7523,5282.4,134.957595,142.416326,2.316576,9.681635,83.847619,-0.203608
27,Toronto Raptors,64,5665,1448,618,924,7231,7606,5391.8,134.111058,141.066063,1.470039,8.331372,84.246875,0.195648
28,Utah Jazz,64,5413,1457,566,954,7106,7658,5218.2,136.177226,146.755586,3.536207,14.020895,81.534375,-2.516852
29,Washington Wizards,64,5821,1584,644,900,7399,8022,5443.4,135.926076,147.371128,3.285057,14.636437,85.053125,1.001898

In [15]:
#Predicting scores
def GameSim(team1, team2):
    team1odiff = np.random.normal(data.loc[data['Team']==team1,'OER'],scale=5)-oeravg
    team1ddiff = np.random.normal(data.loc[data['Team']==team1,'DER'],scale=5)-deravg
    team2odiff = np.random.normal(data.loc[data['Team']==team2,'OER'],scale=5)-oeravg
    team2ddiff = np.random.normal(data.loc[data['Team']==team2,'DER'],scale=5)-deravg
    team1expeff = (oeravg + team1odiff + team2ddiff)*(1.01)
    team2expeff = (oeravg + team2odiff + team1ddiff)*(0.99)
    matchtempo = data.loc[data['Team']==team1,'Tdiff'].to_numpy()+data.loc[data['Team']==team2,'Tdiff'].to_numpy()+tempoavg
    team1score = (team1expeff/100)*matchtempo
    team2score = (team2expeff/100)*matchtempo
    score = [team1score, team2score]
    return score

In [41]:
#Monte Carlo Simulator 
def simulator(team1, team2):
    team1win = 0
    team2win = 0
    team1score = 0
    team2score = 0
    matchcount=0
    for i in range(5000):
        gm = GameSim(team1,team2)
        if gm[0] > gm[1]:
            team1win+=1
        elif gm[0]<gm[1]:
            team2win+=1
        else:
            matchcount-=1
        team1score+=gm[0]
        team2score+=gm[1]
        matchcount+=1
    #if team1win>team2win:
     #   return 1
    #elif team1win<team2win:
     #   return 0
    print(team1, 'chances of winning = ',(team1win/matchcount)*100,'%')
    print(team2, 'chances of winning = ',(team2win/matchcount)*100,'%')
    print(team1, 'possible score = ',(round((team1score/matchcount)[0])))
    print(team2, 'possible score = ',(round((team2score/matchcount)[0])))

In [40]:
#Calling the simulator
#Add the teams from the team list shown in one of the above dataframe
#It takes around 10 to 15 seconds to predict the output
simulator('Los Angeles Lakers', 'Los Angeles Clippers')

Los Angeles Lakers chances of winning =  41.53 %
Los Angeles Clippers chances of winning =  58.47 %
Los Angeles Lakers possible score =  115.0
Los Angeles Clippers possible score =  117.0

In [14]:
#Experimental stuff
#Kindly ignore from here on
match = pd.read_csv('simulate2019.csv')
match.head()

                Date                  Team2                 Team1
0  Mon, Mar 16, 2020     Washington Wizards    Philadelphia 76ers
1  Mon, Mar 16, 2020  Golden State Warriors       Toronto Raptors
2  Mon, Mar 16, 2020             Miami Heat       Milwaukee Bucks
3  Mon, Mar 16, 2020          Atlanta Hawks  New Orleans Pelicans
4  Mon, Mar 16, 2020      Memphis Grizzlies     San Antonio Spurs

In [17]:
[rowm,colm] = match.shape
for i in range(rowm):
    game = simulator(match.loc[i,'Team1'],match.loc[i,'Team2'])
    if game == 1:
        match.loc[i,'PredictedWinner'] = match.loc[i,'Team1']
    elif game ==0:
        match.loc[i,'PredictedWinner'] = match.loc[i,'Team2']

KeyboardInterrupt:

In [34]:
match.loc[13,:]

Date                   Wed, Mar 18, 2020
Team2              Golden State Warriors
Team1                     Indiana Pacers
PredictedWinner           Indiana Pacers
Name: 13, dtype: object